#!/bin/bash

#echo "SSA_amgx: $1"
#echo BASEDIR=${BASEDIR}
#echo SCRIPTSDIR=${SCRIPTSDIR}
#echo CONTAINERSDIR=${CONTAINERSDIR}
#echo INPUTSDIR=${INPUTSDIR}

export CUDA_MPS_LOG_DIRECTORY=./pipe_${SLURM_JOB_ID}_${SLURM_NODEID}
export CUDA_MPS_PIPE_DIRECTORY=./pipe_${SLURM_JOB_ID}_${SLURM_NODEID}

if [ "$SLURM_LOCALID" -eq 0 ]; then
#    mkdir -p $CUDA_MPS_PIPE_DIRECTORY
    nvidia-cuda-mps-control -d
fi

#echo CUDA_MPS_PIPE_DIRECTORY=$CUDA_MPS_PIPE_DIRECTORY

export SINGULARITYENV_CUDA_MPS_PIPE_DIRECTORY=$CUDA_MPS_PIPE_DIRECTORY
export SINGULARITYENV_CUDA_MPS_LOG_DIRECTORY=$CUDA_MPS_LOG_DIRECTORY
#sleep 1

singularity exec -B ${GREENLAND} -B ${NSYS_TMP}:/tmp --env UCX_POSIX_USE_PROC_LINK=n --nv ${CONTAINER} ${PROFILE} ElmerSolver_mpi $1
#singularity exec -B ${RUNDIR}/Greenland_SSA --env UCX_POSIX_USE_PROC_LINK=n --nv ${CONTAINERSDIR}/Elmer_ubuntu24_leonardo.sif ElmerSolver_mpi $1

